# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a0fe02869b8145e94aa969fa805d5a626dfc015b18da9b729515ebefe46fd7451c78f4c49eb6f568476b778f4356d7300fc333548b142f983a9e6f5f8559d4c

test:
  secret_key_base: 59cddab1fbe7a7995629e00a424f62d7303273ab13e989c3c26d83185ddda1e0aa12d54c2f7ba9f3f5322c469076d68dcec46b91000c0e246a7989fafdec9d56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
